// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Stocks.Data;

namespace Stocks.iOS
{
	public partial class MainViewCell : UITableViewCell
	{
		public MainViewCell (IntPtr handle) : base (handle)
		{
		}

        public void LoadView(ItemStock item)
        {
            if(item == null) {
                LabelNameOfCurrency.Text = "None Name";
                LabelAmount.Text = "0.00";
                LabelVolume.Text = "0";

                return;
            }

            LabelNameOfCurrency.Text = !string.IsNullOrEmpty(item.Name) ? item.Name : "None Name";
            LabelAmount.Text = item.Price.Amount.ToString("0.00");
            LabelVolume.Text = item.Volume.ToString();


        }

	}
}
